#!/usr/bin/env bash
#
# upgrade.sh — generate Traefik file-provider config for the shared static Caddy.
#
# Model: adding a site = creating a folder ~/web/static/<hostname>/.
# This scans those folders and emits one Traefik router per hostname, all
# pointing at the single shared Caddy service. Because Traefik only routes the
# hosts listed here, this generated file IS the whitelist.
#
# Output (the generator's own output — the only files it is allowed to replace):
#   ~/web/static/sites.yaml               source of truth
#   ~/web/traefik/dynamic/sites.yaml      installed copy Traefik watches
#
# It never touches any other pre-existing file. Existing outputs are replaced
# in place; writes are atomic (.tmp then mv / cp).
#
set -euo pipefail

# --- self-upgrade: pull the latest version of this script, then re-exec ------
# Runs `git pull` in this script's own repo so the newest upgrade.sh runs.
# The UPGRADE_SH_SELF_UPGRADED guard prevents an infinite re-exec loop: the
# second run sees it set and skips straight past this block.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -z "${UPGRADE_SH_SELF_UPGRADED:-}" ]; then
  if git -C "$SCRIPT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Self-upgrading: git pull in $SCRIPT_DIR ..."
    if git -C "$SCRIPT_DIR" pull --ff-only; then
      export UPGRADE_SH_SELF_UPGRADED=1
      echo "Re-executing upgraded script."
      exec "${BASH_SOURCE[0]}" "$@"
    else
      echo "git pull failed — continuing with the current version." >&2
    fi
  else
    echo "$SCRIPT_DIR is not a git work tree — skipping self-upgrade." >&2
  fi
fi

# --- configuration (matches the live Traefik static config) -----------------
STATIC_DIR="${STATIC_DIR:-$HOME/web/static}"
DYNAMIC_DIR="${DYNAMIC_DIR:-$HOME/web/traefik/dynamic}"
SOURCE_OUT="$STATIC_DIR/sites.yaml"
INSTALLED_OUT="$DYNAMIC_DIR/sites.yaml"

SERVICE_NAME="static-caddy"          # Traefik service key + Caddy container name
SERVICE_URL="http://static-caddy:80" # reachable by name on the pontsun network
ENTRYPOINTS="http,https"             # discovered entrypoint names
CERTRESOLVER="letencrypt"            # discovered resolver name (one 't')

TS="$(date -u +%Y%m%dT%H%M%SZ)"

# --- discover sites ---------------------------------------------------------
# A "site" is a direct subdirectory of STATIC_DIR whose name looks like a
# hostname (contains a dot) and is not hidden. Folder name == hostname.
mapfile -t SITES < <(
  find "$STATIC_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' \
    | grep -E '^[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)+$' \
    | sort
)

if [ "${#SITES[@]}" -eq 0 ]; then
  echo "No site folders (host-like names) found in $STATIC_DIR — nothing to do." >&2
  exit 1
fi

# sanitize a hostname into a Traefik router key: ia.constantin.dev -> static-ia-constantin-dev
router_key() { printf 'static-%s' "$(printf '%s' "$1" | tr -c 'A-Za-z0-9' '-')"; }

# --- build config into a temp file ------------------------------------------
TMP="$(mktemp "$STATIC_DIR/.sites.yaml.tmp.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

{
  echo "# GENERATED by upgrade.sh at ${TS} — do not edit by hand."
  echo "# One router per static site; all share the ${SERVICE_NAME} service."
  echo "http:"
  echo "  routers:"
  for host in "${SITES[@]}"; do
    key="$(router_key "$host")"
    echo "    ${key}:"
    echo "      rule: \"Host(\`${host}\`)\""
    echo "      entryPoints:"
    IFS=',' read -ra EPS <<< "$ENTRYPOINTS"
    for ep in "${EPS[@]}"; do echo "        - ${ep}"; done
    echo "      service: ${SERVICE_NAME}"
    echo "      tls:"
    echo "        certResolver: ${CERTRESOLVER}"
  done
  echo "  services:"
  echo "    ${SERVICE_NAME}:"
  echo "      loadBalancer:"
  echo "        servers:"
  echo "          - url: \"${SERVICE_URL}\""
} > "$TMP"

echo "Discovered ${#SITES[@]} site(s):"
printf '  - %s\n' "${SITES[@]}"

# --- install: replace outputs atomically ------------------------------------
# source of truth
cp -a "$TMP" "$SOURCE_OUT.new.$$"
mv "$SOURCE_OUT.new.$$" "$SOURCE_OUT"
echo "Wrote $SOURCE_OUT"

# installed copy Traefik watches
cp -a "$SOURCE_OUT" "$INSTALLED_OUT.new.$$"
mv "$INSTALLED_OUT.new.$$" "$INSTALLED_OUT"
echo "Installed $INSTALLED_OUT (Traefik will hot-reload it)"

echo "Done."
